### ISSUE TITLE
An :A issue with both phoenix.vim and tpope/vim-rails installed

### ISSUE THREAD

**Issue by mxgrn** [c-brenn/phoenix.vim#2]
When I have both plugins installed, the :A command only works in 1 direction, e.g. from `web/models/contract.ex` to `test/models/contract_test.exs`.

When trying to get back to the model from tests I'm getting `E464: Ambiguous use of user-defined command`.

Hope, you have a moment to look into this - and big thanks for the plugin!

**Comment by c-brenn** [comment]
phoenix.vim uses one of [tpope's plugins - projectionist](https://github.com/tpope/vim-projectionist) to do all of the navigation (`:A`, `:Emodel` etc.)

Just want to confirm that you have the `tpope/vim-projectionist` plugin in your vimrc.

If that's not the issue I'll investigate some more. I expect there are a few ways in which phoenix.vim misbehaves when rails.vim is also installed - this might be one of them but hopefully can be fixed.

**Comment by mxgrn** [comment]
Thanks for looking into this. Yes, I have projectionist installed:

```
Plug 'c-brenn/phoenix.vim'
Plug 'tpope/vim-projectionist'
```

**Comment by c-brenn** [comment]
Sorry for the delay. I've tried to reproduce this locally but can't. In a new phoenix project, I open `web/models/foo.ex`. `:A` prompts me to create a new test file - `test/models/foo_test.exs`, which I do. I save the file. `:A` brings me back to `web/models/foo.ex`.

Does your test file name end in `.exs`?

Closing this for now, but will reopen if the problem persists and can be reproduced.
