### ISSUE TITLE
Issue with tpope/vim-rails

### ISSUE THREAD

**Issue by suaron** [c-brenn/phoenix.vim#3]
As I can see this plugin conflicted with tpope/vim-rails
```:E'Commands'``` does not work if I have enabled both these plugins.

**Comment by c-brenn** [comment]
Yeah, they don't play very nicely together. tpope has mentioned that he plans on moving rails.vim over to use projectionist internally - which might fix everything - but I don't think he's ever gotten around to it.

I'll take a look and see if there's a work around

**Comment by c-brenn** [comment]
Sorry for taking so long to getting around to looking at this.

I tried to reproduce locally but can't. I have both rails.vim and phoenix.vim installed, and both work as expected in rails/phoenix projects.

`:E'Commands` depend on the current file, not the current directory. If you open vim in a phoenix project, the commands only become available when you actually open an elixir file. Perhaps this is the issue? If so, then I should make it more clear in the documentation.
