### ISSUE TITLE
Eview should default to view with current controller's name

### ISSUE THREAD

**Issue by nhooyr** [c-brenn/phoenix.vim#5]
title

I'm not sure this is possible though, given vim-projectionist is creating the commands.

**Comment by c-brenn** [comment]
Unfortunately I don't think this is possible with projectionist's current feature set.

Providing context aware defaults for `Ecommands` would be a nice addition, so I'd be open to merging a PR that added it.

Alternatively, perhaps this feature would fit better upstream - in projectionist.vim.

I'll close this issue for now.
